[package]
name = "rust-monte-carlo-tree-search"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
getrandom = { version = "0.2", features = ["std"] }

[profile.release]
opt-level = 3
lto = true
