[workspace]
authors = ["Giovanni Dejan <giovanni.dejan@binus.ac.id>"]
channels = ["conda-forge"]
name = "rust-monte-carlo-tree-search"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "cargo build"
start = "cargo run"
clean = "cargo clean"
test = "cargo test"
fmt = "cargo fmt"
lint = { cmd = "cargo clippy", depends-on = ["fmt"] }
lint-fix = "cargo clippy --fix --allow-dirty"
doc = "cargo doc"

[dependencies]
rust = ">=1.93.1,<1.94"
